In [1]:
'''
This file plots CMIP5 RCP - HIST over South Australia
/Users/earl/Desktop/Yang
and places the outputs in
/Users/earl/Dropbox/CMIP5/figures

Earl Duran 
created: 19-Mar-18
e.duran@unsw.edu.au
'''

import os
import xarray as xr
import numpy as np
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import matplotlib
import sys
import pickle
import itertools
def find_nearest_index(array, value):
    return int((np.abs(array - value)).argmin())
from scipy import interpolate
from scipy import stats
from dask.distributed import Client

import cartopy.crs as ccrs
import cartopy.feature as cft
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
def arange(start,end,stride=1):
    return np.arange(start,end+0.00000001,stride)

import cosima_cookbook as cc
import sys, os
sys.path.append(os.path.join(os.getcwd(), '..'))  # so we can import ../exptdata
import exptdata
print('Available exptdata keys: ', [k for k in exptdata.exptdict.keys()])
session = cc.database.create_session()

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

netcdf_index loaded.
Available exptdata keys:  ['1deg', '025deg', '01deg']

AttributeError: module 'cosima_cookbook' has no attribute 'database'

In [2]:
%%javascript
IPython.notebook.kernel.execute('nb_name = ' + '"' + IPython.notebook.notebook_name + '"')

In [3]:
client = Client()
client

In [4]:
# input_path = '/g/data/e14/erd561/NOAA_OI_SST_V2/'

output_path = '/g/data/e14/erd561/Australia_3/'

In [5]:
%%time
latS = -70
latN = 20
lonW = 90-360
lonE = 180-360
ekey='1deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

sea_level_z0_1_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean_month.nc',
                                     variable='eta_t').\
sel(yt_ocean=slice(latS,latN)).\
sel(xt_ocean=slice(lonW,lonE))
print(sea_level_z0_1_mod_month)

sea_level_z0_1_mod_month.load()
print(sea_level_z0_1_mod_month)

xt_ocean = sea_level_z0_1_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
sea_level_z0_1_mod_month = sea_level_z0_1_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
print(sea_level_z0_1_mod_month)

sea_level_z0_1_mod = sea_level_z0_1_mod_month.groupby('time.year').mean('time')
print(sea_level_z0_1_mod)

sea_level_z0_1_mod = sea_level_z0_1_mod.sel(year=slice(1993+60*4,2017+60*4))
print(sea_level_z0_1_mod)

1deg_jra55v13_iaf_spinup1_B1

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: In xarray version 0.13 `auto_combine` will be deprecated.
  coords=coords)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset` to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in in future, please use the
new `combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  coords=coords)

<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 160, xt_ocean: 90)>
dask.array<shape=(3600, 160, 90), dtype=float32, chunksize=(1, 160, 90)>
Coordinates:
  * xt_ocean  (xt_ocean) float64 -269.5 -268.5 -267.5 ... -182.5 -181.5 -180.5
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * time      (time) object 1958-01-16 12:00:00 ... 2257-12-16 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t
<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 160, xt_ocean: 90)>
array([[[      nan,       nan, ..., -1.578523, -1.573317],
        [      nan,       nan, ..., -1.571597, -1.565494],
        ...,
        [ 0.506732,  0.498771, ...,  0.654748,  0.652205],
        [ 0.495682,  0.477471, ...,  0.642568,  0.640273]],

       [[      nan,       nan, ..., -1.642074, -1.63865 ],
        [      nan,       nan, ..., -1.636303, -1.633056],
        ...,
        [ 0.431764,  0.412046, ...,  0.693105,  0.687378],
        [ 0.40691 ,  0.385409, ...,  0.684598,  0.681622]],

       ...,

       [[      nan,       nan, ..., -1.811454, -1.809794],
        [      nan,       nan, ..., -1.805154, -1.802366],
        ...,
        [ 0.63337 ,  0.65387 , ...,  0.740889,  0.741569],
        [ 0.653126,  0.661706, ...,  0.7295  ,  0.729541]],

       [[      nan,       nan, ..., -1.791747, -1.789826],
        [      nan,       nan, ..., -1.785287, -1.782203],
        ...,
        [ 0.615872,  0.632522, ...,  0.732524,  0.730576],
        [ 0.629312,  0.634262, ...,  0.725007,  0.722264]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 -269.5 -268.5 -267.5 ... -182.5 -181.5 -180.5
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * time      (time) object 1958-01-16 12:00:00 ... 2257-12-16 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t
<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 160, xt_ocean: 90)>
array([[[      nan,       nan, ..., -1.578523, -1.573317],
        [      nan,       nan, ..., -1.571597, -1.565494],
        ...,
        [ 0.506732,  0.498771, ...,  0.654748,  0.652205],
        [ 0.495682,  0.477471, ...,  0.642568,  0.640273]],

       [[      nan,       nan, ..., -1.642074, -1.63865 ],
        [      nan,       nan, ..., -1.636303, -1.633056],
        ...,
        [ 0.431764,  0.412046, ...,  0.693105,  0.687378],
        [ 0.40691 ,  0.385409, ...,  0.684598,  0.681622]],

       ...,

       [[      nan,       nan, ..., -1.811454, -1.809794],
        [      nan,       nan, ..., -1.805154, -1.802366],
        ...,
        [ 0.63337 ,  0.65387 , ...,  0.740889,  0.741569],
        [ 0.653126,  0.661706, ...,  0.7295  ,  0.729541]],

       [[      nan,       nan, ..., -1.791747, -1.789826],
        [      nan,       nan, ..., -1.785287, -1.782203],
        ...,
        [ 0.615872,  0.632522, ...,  0.732524,  0.730576],
        [ 0.629312,  0.634262, ...,  0.725007,  0.722264]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * time      (time) object 1958-01-16 12:00:00 ... 2257-12-16 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:160: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)

<xarray.DataArray 'eta_t' (year: 300, yt_ocean: 160, xt_ocean: 90)>
array([[[      nan,       nan, ..., -1.670531, -1.666994],
        [      nan,       nan, ..., -1.663988, -1.660291],
        ...,
        [ 0.479797,  0.487803, ...,  0.697266,  0.691195],
        [ 0.488086,  0.491912, ...,  0.694398,  0.68832 ]],

       [[      nan,       nan, ..., -1.676496, -1.67766 ],
        [      nan,       nan, ..., -1.664565, -1.665094],
        ...,
        [ 0.536418,  0.543263, ...,  0.690036,  0.685242],
        [ 0.54945 ,  0.551747, ...,  0.689748,  0.684691]],

       ...,

       [[      nan,       nan, ..., -1.801003, -1.79937 ],
        [      nan,       nan, ..., -1.795574, -1.793039],
        ...,
        [ 0.624408,  0.632264, ...,  0.690162,  0.68675 ],
        [ 0.636086,  0.638092, ...,  0.686346,  0.683252]],

       [[      nan,       nan, ..., -1.803916, -1.802256],
        [      nan,       nan, ..., -1.797055, -1.794382],
        ...,
        [ 0.615035,  0.622452, ...,  0.736722,  0.737148],
        [ 0.624793,  0.626524, ...,  0.725082,  0.726301]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * year      (year) int64 1958 1959 1960 1961 1962 ... 2253 2254 2255 2256 2257
<xarray.DataArray 'eta_t' (year: 25, yt_ocean: 160, xt_ocean: 90)>
array([[[      nan,       nan, ..., -1.804237, -1.802819],
        [      nan,       nan, ..., -1.802441, -1.800091],
        ...,
        [ 0.570624,  0.572101, ...,  0.660109,  0.655128],
        [ 0.579468,  0.574604, ...,  0.654862,  0.649933]],

       [[      nan,       nan, ..., -1.79727 , -1.795696],
        [      nan,       nan, ..., -1.795215, -1.792714],
        ...,
        [ 0.552581,  0.553011, ...,  0.63699 ,  0.632463],
        [ 0.559259,  0.554437, ...,  0.629591,  0.62374 ]],

       ...,

       [[      nan,       nan, ..., -1.801003, -1.79937 ],
        [      nan,       nan, ..., -1.795574, -1.793039],
        ...,
        [ 0.624408,  0.632264, ...,  0.690162,  0.68675 ],
        [ 0.636086,  0.638092, ...,  0.686346,  0.683252]],

       [[      nan,       nan, ..., -1.803916, -1.802256],
        [      nan,       nan, ..., -1.797055, -1.794382],
        ...,
        [ 0.615035,  0.622452, ...,  0.736722,  0.737148],
        [ 0.624793,  0.626524, ...,  0.725082,  0.726301]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * year      (year) int64 2233 2234 2235 2236 2237 ... 2253 2254 2255 2256 2257
CPU times: user 13.1 s, sys: 1.85 s, total: 15 s
Wall time: 27.6 s

In [6]:
year = sea_level_z0_1_mod.year
lat_1_mod = sea_level_z0_1_mod.yt_ocean
lon_1_mod = sea_level_z0_1_mod.xt_ocean

sea_level_z0_1_trans_mod = sea_level_z0_1_mod
print(np.shape(sea_level_z0_1_trans_mod))
sea_level_z0_1_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='sea_level_z0_1')
sea_level_z0_1_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='sea_level_z0_1')
sea_level_z0_1_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='sea_level_z0_1')
for iid, i in enumerate(lat_1_mod):
    for jid, j in enumerate(lon_1_mod):
        sea_level_z0_1_slope_mod[iid, jid], _, _, sea_level_z0_1_p_value_mod[iid, jid], sea_level_z0_1_std_err_mod[iid, jid] = \
        stats.linregress(year, sea_level_z0_1_trans_mod[:, iid, jid])
    print('lat_1_mod ' + str(np.array(i)))
print(sea_level_z0_1_slope_mod)

(25, 160, 90)
lat_1_mod -69.6292858330716
lat_1_mod -69.17632154294074
lat_1_mod -68.70935410409521
lat_1_mod -68.22843658249317
lat_1_mod -67.73301847540898
lat_1_mod -67.2232002021303
lat_1_mod -66.69847936238045
lat_1_mod -66.15900514695375
lat_1_mod -65.60432451496254
lat_1_mod -65.03463652231858
lat_1_mod -64.44953841598465
lat_1_mod -63.84927987875662
lat_1_mod -63.233509039251814
lat_1_mod -62.602526632003375
lat_1_mod -61.95603192247815
lat_1_mod -61.29437678205883
lat_1_mod -60.61731152794955
lat_1_mod -59.92523891318751
lat_1_mod -59.21795988186098
lat_1_mod -58.49592747485757
lat_1_mod -57.75899250138302
lat_1_mod -57.00765736171395
lat_1_mod -56.24182163656275
lat_1_mod -55.46203582865502
lat_1_mod -54.66824687203264
lat_1_mod -53.86105179481633
lat_1_mod -53.04044315107174
lat_1_mod -52.20706260764199
lat_1_mod -51.36094630171701
lat_1_mod -50.50277835512628
lat_1_mod -49.63263616124607
lat_1_mod -48.751243830625256
lat_1_mod -47.858717411335334
lat_1_mod -46.955818270259286
lat_1_mod -46.04269825143213
lat_1_mod -45.12015299775091
lat_1_mod -44.1883670522662
lat_1_mod -43.24816712546786
lat_1_mod -42.299767144867545
lat_1_mod -41.34402147337693
lat_1_mod -40.381169912865516
lat_1_mod -39.412090879473524
lat_1_mod -38.437046367135494
lat_1_mod -37.45693508595663
lat_1_mod -36.47203739195916
lat_1_mod -35.483268394896754
lat_1_mod -34.490922860705325
lat_1_mod -33.4959282953335
lat_1_mod -32.49858982656124
lat_1_mod -31.499843270584066
lat_1_mod -30.500000000000007
lat_1_mod -29.499999999999993
lat_1_mod -28.500913643497
lat_1_mod -27.508207772936977
lat_1_mod -26.52362975930542
lat_1_mod -25.552487488607724
lat_1_mod -24.59629207651681
lat_1_mod -23.660040443316156
lat_1_mod -22.744861435552927
lat_1_mod -21.855302589201557
lat_1_mod -20.991981174865394
lat_1_mod -20.158876565873385
lat_1_mod -19.355987508390562
lat_1_mod -18.586631266197905
lat_1_mod -17.850108145013586
lat_1_mod -17.14900828953254
lat_1_mod -16.481884174216546
lat_1_mod -15.850565593729577
lat_1_mod -15.252840484281915
lat_1_mod -14.689778290506553
lat_1_mod -14.158419117357393
lat_1_mod -13.659105290381383
lat_1_mod -13.188178474085568
lat_1_mod -12.745318884468919
lat_1_mod -12.326249661600169
lat_1_mod -11.930082858832805
lat_1_mod -11.55203004029174
lat_1_mod -11.190753875021418
lat_1_mod -10.841083658020995
lat_1_mod -10.501371092612995
lat_1_mod -10.16620921848401
lat_1_mod -9.83379078151599
lat_1_mod -9.499542551884009
lat_1_mod -9.167124114915989
lat_1_mod -8.832875885284007
lat_1_mod -8.500457448315988
lat_1_mod -8.166209218684006
lat_1_mod -7.833790781715987
lat_1_mod -7.499542552084007
lat_1_mod -7.167124115115987
lat_1_mod -6.8328758854840075
lat_1_mod -6.500457448515988
lat_1_mod -6.166209218884008
lat_1_mod -5.833790781915988
lat_1_mod -5.499542552284009
lat_1_mod -5.167124115315989
lat_1_mod -4.832875885684009
lat_1_mod -4.50045744871599
lat_1_mod -4.16620921908401
lat_1_mod -3.8337907821159902
lat_1_mod -3.4995425524840096
lat_1_mod -3.16712411551599
lat_1_mod -2.8328758858840093
lat_1_mod -2.5004574489159896
lat_1_mod -2.166209219284009
lat_1_mod -1.8337907823159894
lat_1_mod -1.4995425526840092
lat_1_mod -1.1671241157159895
lat_1_mod -0.8328758860840093
lat_1_mod -0.5004574491159897
lat_1_mod -0.16620921948400935
lat_1_mod 0.1662092174840103
lat_1_mod 0.5004574471159906
lat_1_mod 0.8328758840840103
lat_1_mod 1.1671241137159905
lat_1_mod 1.49954255068401
lat_1_mod 1.8337907803159903
lat_1_mod 2.1662092172840097
lat_1_mod 2.5004574469159904
lat_1_mod 2.83287588388401
lat_1_mod 3.1671241135159907
lat_1_mod 3.4995425504840103
lat_1_mod 3.833790780115991
lat_1_mod 4.166209217084011
lat_1_mod 4.50045744671599
lat_1_mod 4.83287588368401
lat_1_mod 5.16712411331599
lat_1_mod 5.499542550284009
lat_1_mod 5.833790779915989
lat_1_mod 6.166209216884009
lat_1_mod 6.500457446515989
lat_1_mod 6.832875883484008
lat_1_mod 7.167124113115988
lat_1_mod 7.499542550084008
lat_1_mod 7.833790779715987
lat_1_mod 8.166209216684006
lat_1_mod 8.500457446315988
lat_1_mod 8.832875883284007
lat_1_mod 9.167124112915989
lat_1_mod 9.499542549884008
lat_1_mod 9.83379077951599
lat_1_mod 10.16620922048401
lat_1_mod 10.501371089612988
lat_1_mod 10.841083660020995
lat_1_mod 11.19075387202141
lat_1_mod 11.55203004229174
lat_1_mod 11.930082855832797
lat_1_mod 12.32624966360017
lat_1_mod 12.745318881468911
lat_1_mod 13.188178476085568
lat_1_mod 13.659105287381376
lat_1_mod 14.158419119357394
lat_1_mod 14.689778287506545
lat_1_mod 15.252840486281915
lat_1_mod 15.85056559072957
lat_1_mod 16.48188417621655
lat_1_mod 17.14900828653253
lat_1_mod 17.85010814701359
lat_1_mod 18.586631263197898
lat_1_mod 19.355987510390566
<xarray.DataArray 'sea_level_z0_1' (lat_1: 160, lon_1: 90)>
array([[      nan,       nan,       nan, ..., -0.000443, -0.000411, -0.000392],
       [      nan,       nan,       nan, ..., -0.000392, -0.000361, -0.000339],
       [      nan,       nan,       nan, ..., -0.000365, -0.000341, -0.000331],
       ...,
       [ 0.001265,  0.001428,  0.0016  , ...,  0.000902,  0.000939,  0.000975],
       [ 0.001355,  0.001509,  0.001669, ...,  0.000865,  0.000918,  0.000963],
       [ 0.001435,  0.001606,  0.001793, ...,  0.000781,  0.000857,  0.000913]])
Coordinates:
  * lat_1    (lat_1) float64 -69.63 -69.18 -68.71 -68.23 ... 17.85 18.59 19.36
  * lon_1    (lon_1) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5

In [7]:
%%time
latS = -70
latN = 20
lonW = 90-360
lonE = 180-360
ekey='025deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

sea_level_z0_025_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean_month.nc',
                                     variable='eta_t').\
sel(yt_ocean=slice(latS,latN)).\
sel(xt_ocean=slice(lonW,lonE))
print(sea_level_z0_025_mod_month)

sea_level_z0_025_mod_month.load()
print(sea_level_z0_025_mod_month)

xt_ocean = sea_level_z0_025_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
sea_level_z0_025_mod_month = sea_level_z0_025_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
print(sea_level_z0_025_mod_month)

sea_level_z0_025_mod = sea_level_z0_025_mod_month.groupby('time.year').mean('time')
print(sea_level_z0_025_mod)

sea_level_z0_025_mod = sea_level_z0_025_mod.sel(year=slice(1993+60*4,2017+60*4))
print(sea_level_z0_025_mod)

025deg_jra55v13_iaf_gmredi6

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: In xarray version 0.13 `auto_combine` will be deprecated.
  coords=coords)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset` to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in in future, please use the
new `combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  coords=coords)

<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 475, xt_ocean: 360)>
dask.array<shape=(3600, 475, 360), dtype=float32, chunksize=(1, 435, 360)>
Coordinates:
  * xt_ocean  (xt_ocean) float64 -269.9 -269.6 -269.4 ... -180.6 -180.4 -180.1
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * time      (time) object 1958-01-14 12:00:00 ... 2257-12-14 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t
<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 475, xt_ocean: 360)>
array([[[      nan,       nan, ..., -1.67311 , -1.671141],
        [      nan,       nan, ..., -1.671933, -1.669703],
        ...,
        [ 0.498718,  0.494208, ...,  0.676084,  0.676236],
        [ 0.485181,  0.4802  , ...,  0.667175,  0.668153]],

       [[      nan,       nan, ..., -1.716967, -1.715132],
        [      nan,       nan, ..., -1.717723, -1.715832],
        ...,
        [ 0.407176,  0.39623 , ...,  0.69587 ,  0.696411],
        [ 0.390388,  0.384076, ...,  0.687637,  0.688529]],

       ...,

       [[      nan,       nan, ..., -1.794099, -1.792826],
        [      nan,       nan, ..., -1.795675, -1.793953],
        ...,
        [ 0.588332,  0.59144 , ...,  0.666553,  0.666224],
        [ 0.598248,  0.603383, ...,  0.669799,  0.67024 ]],

       [[      nan,       nan, ..., -1.780645, -1.77942 ],
        [      nan,       nan, ..., -1.781929, -1.780394],
        ...,
        [ 0.570077,  0.571398, ...,  0.697146,  0.696451],
        [ 0.579374,  0.5838  , ...,  0.70151 ,  0.701694]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 -269.9 -269.6 -269.4 ... -180.6 -180.4 -180.1
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * time      (time) object 1958-01-14 12:00:00 ... 2257-12-14 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t
<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 475, xt_ocean: 360)>
array([[[      nan,       nan, ..., -1.67311 , -1.671141],
        [      nan,       nan, ..., -1.671933, -1.669703],
        ...,
        [ 0.498718,  0.494208, ...,  0.676084,  0.676236],
        [ 0.485181,  0.4802  , ...,  0.667175,  0.668153]],

       [[      nan,       nan, ..., -1.716967, -1.715132],
        [      nan,       nan, ..., -1.717723, -1.715832],
        ...,
        [ 0.407176,  0.39623 , ...,  0.69587 ,  0.696411],
        [ 0.390388,  0.384076, ...,  0.687637,  0.688529]],

       ...,

       [[      nan,       nan, ..., -1.794099, -1.792826],
        [      nan,       nan, ..., -1.795675, -1.793953],
        ...,
        [ 0.588332,  0.59144 , ...,  0.666553,  0.666224],
        [ 0.598248,  0.603383, ...,  0.669799,  0.67024 ]],

       [[      nan,       nan, ..., -1.780645, -1.77942 ],
        [      nan,       nan, ..., -1.781929, -1.780394],
        ...,
        [ 0.570077,  0.571398, ...,  0.697146,  0.696451],
        [ 0.579374,  0.5838  , ...,  0.70151 ,  0.701694]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * time      (time) object 1958-01-14 12:00:00 ... 2257-12-14 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:160: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)

<xarray.DataArray 'eta_t' (year: 300, yt_ocean: 475, xt_ocean: 360)>
array([[[      nan,       nan, ..., -1.71599 , -1.714387],
        [      nan,       nan, ..., -1.718057, -1.716083],
        ...,
        [ 0.465696,  0.468237, ...,  0.686613,  0.684455],
        [ 0.471382,  0.473248, ...,  0.683246,  0.681214]],

       [[      nan,       nan, ..., -1.723436, -1.720746],
        [      nan,       nan, ..., -1.726769, -1.723956],
        ...,
        [ 0.511942,  0.512129, ...,  0.664635,  0.662409],
        [ 0.518589,  0.518891, ...,  0.661631,  0.660411]],

       ...,

       [[      nan,       nan, ..., -1.787297, -1.785659],
        [      nan,       nan, ..., -1.789853, -1.787913],
        ...,
        [ 0.592735,  0.593659, ...,  0.652826,  0.650117],
        [ 0.598827,  0.599599, ...,  0.652331,  0.65008 ]],

       [[      nan,       nan, ..., -1.791817, -1.790245],
        [      nan,       nan, ..., -1.793794, -1.791964],
        ...,
        [ 0.561295,  0.561771, ...,  0.714924,  0.711348],
        [ 0.566657,  0.567885, ...,  0.715818,  0.713085]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * year      (year) int64 1958 1959 1960 1961 1962 ... 2253 2254 2255 2256 2257
<xarray.DataArray 'eta_t' (year: 25, yt_ocean: 475, xt_ocean: 360)>
array([[[      nan,       nan, ..., -1.789115, -1.786906],
        [      nan,       nan, ..., -1.795144, -1.792828],
        ...,
        [ 0.54418 ,  0.545191, ...,  0.630259,  0.629798],
        [ 0.550106,  0.55009 , ...,  0.623799,  0.623284]],

       [[      nan,       nan, ..., -1.777881, -1.776043],
        [      nan,       nan, ..., -1.783839, -1.781937],
        ...,
        [ 0.530977,  0.528909, ...,  0.606088,  0.604389],
        [ 0.534646,  0.532006, ...,  0.603604,  0.601926]],

       ...,

       [[      nan,       nan, ..., -1.787297, -1.785659],
        [      nan,       nan, ..., -1.789853, -1.787913],
        ...,
        [ 0.592735,  0.593659, ...,  0.652826,  0.650117],
        [ 0.598827,  0.599599, ...,  0.652331,  0.65008 ]],

       [[      nan,       nan, ..., -1.791817, -1.790245],
        [      nan,       nan, ..., -1.793794, -1.791964],
        ...,
        [ 0.561295,  0.561771, ...,  0.714924,  0.711348],
        [ 0.566657,  0.567885, ...,  0.715818,  0.713085]]], dtype=float32)
Coordinates:
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * year      (year) int64 2233 2234 2235 2236 2237 ... 2253 2254 2255 2256 2257
CPU times: user 39.2 s, sys: 8.86 s, total: 48.1 s
Wall time: 1min 24s

In [8]:
lat_025_mod = sea_level_z0_025_mod.yt_ocean
lon_025_mod = sea_level_z0_025_mod.xt_ocean

sea_level_z0_025_trans_mod = sea_level_z0_025_mod
print(np.shape(sea_level_z0_025_trans_mod))
sea_level_z0_025_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='sea_level_z0_025')
sea_level_z0_025_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='sea_level_z0_025')
sea_level_z0_025_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='sea_level_z0_025')
for iid, i in enumerate(lat_025_mod):
    for jid, j in enumerate(lon_025_mod):
        sea_level_z0_025_slope_mod[iid, jid], _, _, sea_level_z0_025_p_value_mod[iid, jid], sea_level_z0_025_std_err_mod[iid, jid] = \
        stats.linregress(year, sea_level_z0_025_trans_mod[:, iid, jid])
    print('lat_025_mod ' + str(np.array(i)))
print(sea_level_z0_025_slope_mod)

(25, 475, 360)
lat_025_mod -69.98914896732052
lat_025_mod -69.8835503781156
lat_025_mod -69.77795178891068
lat_025_mod -69.67235319970577
lat_025_mod -69.56675461050085
lat_025_mod -69.46115602129593
lat_025_mod -69.35555743209102
lat_025_mod -69.2499588428861
lat_025_mod -69.14436025368119
lat_025_mod -69.03876166447627
lat_025_mod -68.93316307527135
lat_025_mod -68.82756448606644
lat_025_mod -68.72196589686152
lat_025_mod -68.6163673076566
lat_025_mod -68.51076871845169
lat_025_mod -68.40517012924677
lat_025_mod -68.29957154004185
lat_025_mod -68.19397295083694
lat_025_mod -68.08837436163202
lat_025_mod -67.9827757724271
lat_025_mod -67.87717718322219
lat_025_mod -67.77157859401727
lat_025_mod -67.66598000481235
lat_025_mod -67.56038141560744
lat_025_mod -67.45478282640252
lat_025_mod -67.3491842371976
lat_025_mod -67.24358564799269
lat_025_mod -67.13798705878777
lat_025_mod -67.03238846958286
lat_025_mod -66.92678988037794
lat_025_mod -66.82119129117302
lat_025_mod -66.7155927019681
lat_025_mod -66.60999411276319
lat_025_mod -66.50439552355827
lat_025_mod -66.39879693435336
lat_025_mod -66.29319834514844
lat_025_mod -66.18759975594352
lat_025_mod -66.0820011667386
lat_025_mod -65.97640257753369
lat_025_mod -65.87080398832877
lat_025_mod -65.76520539912386
lat_025_mod -65.65960680991894
lat_025_mod -65.55400822071402
lat_025_mod -65.44840963150911
lat_025_mod -65.34281104230419
lat_025_mod -65.23721245309927
lat_025_mod -65.13161386389436
lat_025_mod -65.02601527468944
lat_025_mod -64.92025344217696
lat_025_mod -64.81407563098301
lat_025_mod -64.70747494548625
lat_025_mod -64.6004556755019
lat_025_mod -64.49301097092135
lat_025_mod -64.3851450793148
lat_025_mod -64.27685119595151
lat_025_mod -64.16813352687055
lat_025_mod -64.0589853125948
lat_025_mod -63.9494107183501
lat_025_mod -63.83940302979951
lat_025_mod -63.72896637207781
lat_025_mod -63.618094075885544
lat_025_mod -63.50679022699296
lat_025_mod -63.39504820104632
lat_025_mod -63.282872045182316
lat_025_mod -63.17025517991206
lat_025_mod -63.05720161447432
lat_025_mod -62.94370481417521
lat_025_mod -62.82976875109592
lat_025_mod -62.71538693527877
lat_025_mod -62.60056330239257
lat_025_mod -62.485291407168205
lat_025_mod -62.369575149612274
lat_025_mod -62.253408129107726
lat_025_mod -62.136794210754246
lat_025_mod -62.01972703856161
lat_025_mod -61.90221044348306
lat_025_mod -61.784238114141246
lat_025_mod -61.665813848108755
lat_025_mod -61.54693137861854
lat_025_mod -61.427594470633736
lat_025_mod -61.307796902006366
lat_025_mod -61.1875424058669
lat_025_mod -61.06682480470665
lat_025_mod -60.945647800605805
lat_025_mod -60.824005260726665
lat_025_mod -60.70190085688727
lat_025_mod -60.57932850096412
lat_025_mod -60.45629183530705
lat_025_mod -60.33278481656153
lat_025_mod -60.20881105840907
lat_025_mod -60.084364562330435
lat_025_mod -59.95944891414468
lat_025_mod -59.83405816024584
lat_025_mod -59.70819585940245
lat_025_mod -59.581856103011404
lat_025_mod -59.45504242360883
lat_025_mod -59.32774895769571
lat_025_mod -59.19997921240009
lat_025_mod -59.071727369439934
lat_025_mod -58.942996911365846
lat_025_mod -58.81378206523734
lat_025_mod -58.68408628986453
lat_025_mod -58.55390385778473
lat_025_mod -58.42323820491095
lat_025_mod -58.29208364940619
lat_025_mod -58.16044360513618
lat_025_mod -58.02831243604918
lat_025_mod -57.89569353481996
lat_025_mod -57.76258131135323
lat_025_mod -57.62897913799566
lat_025_mod -57.4948814707912
lat_025_mod -57.360291662627816
lat_025_mod -57.22520421588314
lat_025_mod -57.08962246486236
lat_025_mod -56.95354095848275
lat_025_mod -56.816963013349266
lat_025_mod -56.67988322513629
lat_025_mod -56.542304893637656
lat_025_mod -56.40422266151375
lat_025_mod -56.26563981264301
lat_025_mod -56.12655103691214
lat_025_mod -55.98695960318641
lat_025_mod -55.84686024883049
lat_025_mod -55.706256228605255
lat_025_mod -55.56514232761621
lat_025_mod -55.423521787435156
lat_025_mod -55.281389441182455
lat_025_mod -55.13874851816258
lat_025_mod -54.99559389979584
lat_025_mod -54.85192880404753
lat_025_mod -54.70774816093398
lat_025_mod -54.56305517801577
lat_025_mod -54.417844834212126
lat_025_mod -54.2721203276197
lat_025_mod -54.1258766863782
lat_025_mod -53.97911710006729
lat_025_mod -53.831836646375294
lat_025_mod -53.68403850731792
lat_025_mod -53.5357178104707
lat_025_mod -53.386877731244375
lat_025_mod -53.23751344745048
lat_025_mod -53.08762812885966
lat_025_mod -52.93721700387838
lat_025_mod -52.78628323760774
lat_025_mod -52.634822109417904
lat_025_mod -52.48283678071659
lat_025_mod -52.330322582216155
lat_025_mod -52.17728267261248
lat_025_mod -52.02371243434808
lat_025_mod -51.86961502439378
lat_025_mod -51.71498587731948
lat_025_mod -51.55982814936279
lat_025_mod -51.40413732762721
lat_025_mod -51.24791656861383
lat_025_mod -51.09116141237475
lat_025_mod -50.93387501667585
lat_025_mod -50.776052974941294
lat_025_mod -50.61769844720747
lat_025_mod -50.458807080702314
lat_025_mod -50.29938203874258
lat_025_mod -50.139419022799565
lat_025_mod -49.978921200484145
lat_025_mod -49.81788432795817
lat_025_mod -49.656311578144
lat_025_mod -49.49419876234849
lat_025_mod -49.33154905982618
lat_025_mod -49.16835833749031
lat_025_mod -49.00462978195127
lat_025_mod -48.84035931619663
lat_025_mod -48.67555013521901
lat_025_mod -48.51019821855441
lat_025_mod -48.34430677060639
lat_025_mod -48.17787182793927
lat_025_mod -48.01089660539825
lat_025_mod -47.84337719706126
lat_025_mod -47.67531682924737
lat_025_mod -47.50671165403836
lat_025_mod -47.33756491026068
lat_025_mod -47.16787280849464
lat_025_mod -46.99763860110834
lat_025_mod -46.82685855767941
lat_025_mod -46.655535945152195
lat_025_mod -46.48366709260396
lat_025_mod -46.31125528258984
lat_025_mod -46.1382969041921
lat_025_mod -45.96479525661064
lat_025_mod -45.79074678944065
lat_025_mod -45.6161548195597
lat_025_mod -45.441015857585846
lat_025_mod -45.26533323910572
lat_025_mod -45.089103536271594
lat_025_mod -44.91233010440849
lat_025_mod -44.735009577715175
lat_025_mod -44.557145332281756
lat_025_mod -44.37873406486607
lat_025_mod -44.19977917334686
lat_025_mod -44.020277417553295
lat_025_mod -43.84023221817254
lat_025_mod -43.65964039861644
lat_025_mod -43.47850540339607
lat_025_mod -43.29682412001572
lat_025_mod -43.1146000178209
lat_025_mod -42.93183004891588
lat_025_mod -42.748517708485565
lat_025_mod -42.564660013738866
lat_025_mod -42.38026048669883
lat_025_mod -42.19531621018006
lat_025_mod -42.00983073403561
lat_025_mod -41.82380120718251
lat_025_mod -41.637231208288156
lat_025_mod -41.45011795286375
lat_025_mod -41.262465049367066
lat_025_mod -41.07426978038944
lat_025_mod -40.88553578514614
lat_025_mod -40.696260413788075
lat_025_mod -40.506447337245405
lat_025_mod -40.31609397370077
lat_025_mod -40.125204026746204
lat_025_mod -39.93377498306014
lat_025_mod -39.7418105798323
lat_025_mod -39.549308372692096
lat_025_mod -39.35627213335076
lat_025_mod -39.16269948683419
lat_025_mod -38.96859424028622
lat_025_mod -38.77395408856423
lat_025_mod -38.5787828751422
lat_025_mod -38.383078365132626
lat_025_mod -38.18684443922285
lat_025_mod -37.9900789331919
lat_025_mod -37.792785765808524
lat_025_mod -37.59496284391664
lat_025_mod -37.39661412521846
lat_025_mod -37.19773758800722
lat_025_mod -36.998337229753794
lat_025_mod -36.798411100570355
lat_025_mod -36.59796323851397
lat_025_mod -36.39699176586966
lat_025_mod -36.19550076207968
lat_025_mod -35.993488421939226
lat_025_mod -35.79095886705533
lat_025_mod -35.58791036505317
lat_025_mod -35.38434708046389
lat_025_mod -35.18026735404409
lat_025_mod -34.975675393987224
lat_025_mod -34.77056961446342
lat_025_mod -34.564954268044595
lat_025_mod -34.358827842576346
lat_025_mod -34.15219463570234
lat_025_mod -33.9450532091844
lat_025_mod -33.73740790640746
lat_025_mod -33.52925736326836
lat_025_mod -33.320605969538136
lat_025_mod -33.11145243544443
lat_025_mod -32.901801197763746
lat_025_mod -32.69165104122648
lat_025_mod -32.48100645020757
lat_025_mod -32.269866284087364
lat_025_mod -32.05823507540491
lat_025_mod -31.846111758312045
lat_025_mod -31.63350091404954
lat_025_mod -31.420401551635727
lat_025_mod -31.20681830152168
lat_025_mod -30.992750247659814

lat_025_mod -30.778202070190314
lat_025_mod -30.56317292803898
lat_025_mod -30.34766755148325
lat_025_mod -30.131685174432455
lat_025_mod -29.915230577717967
lat_025_mod -29.698303070212805
lat_025_mod -29.480907483686703
lat_025_mod -29.2630432019257
lat_025_mod -29.044715107989248
lat_025_mod -28.82592266049411
lat_025_mod -28.606670794106993
lat_025_mod -28.38695904216067
lat_025_mod -28.166792391212045
lat_025_mod -27.946170449161986
lat_025_mod -27.72509825470525
lat_025_mod -27.50357549012893
lat_025_mod -27.28160724647727
lat_025_mod -27.059193280207044
lat_025_mod -26.83633873488693
lat_025_mod -26.61304344089147
lat_025_mod -26.389312594451354
lat_025_mod -26.165146099570944
lat_025_mod -25.940549205242547
lat_025_mod -25.715521888775697
lat_025_mod -25.490069451985352
lat_025_mod -25.264191945124278
lat_025_mod -25.037894722851966
lat_025_mod -24.811177907964588
lat_025_mod -24.58404690794839
lat_025_mod -24.356501917704698
lat_025_mod -24.12854839748857
lat_025_mod -23.90018661382929
lat_025_mod -23.671422079652153
lat_025_mod -23.442255132597825
lat_025_mod -23.212691338122195
lat_025_mod -22.982731104420896
lat_025_mod -22.75238004929935
lat_025_mod -22.52163865091151
lat_025_mod -22.290512579189507
lat_025_mod -22.05900238160839
lat_025_mod -21.827113779962115
lat_025_mod -21.594847390368724
lat_025_mod -21.362208986176793
lat_025_mod -21.129199251428126
lat_025_mod -20.89582401067619
lat_025_mod -20.66208401512598
lat_025_mod -20.427985140143456
lat_025_mod -20.193528203294715
lat_025_mod -19.958719130323008
lat_025_mod -19.723558804311843
lat_025_mod -19.48805320090374
lat_025_mod -19.252203267814213
lat_025_mod -19.016015030064167
lat_025_mod -18.77948949907405
lat_025_mod -18.542632748679452
lat_025_mod -18.30544585303702
lat_025_mod -18.06793493419064
lat_025_mod -17.830101128022857
lat_025_mod -17.591950604136887
lat_025_mod -17.35348455908949
lat_025_mod -17.114709209351908
lat_025_mod -16.875625811062203
lat_025_mod -16.636240626826247
lat_025_mod -16.396554971229563
lat_025_mod -16.156575152237487
lat_025_mod -15.916302541708545
lat_025_mod -15.675743492150964
lat_025_mod -15.434899431481558
lat_025_mod -15.193776755893923
lat_025_mod -14.952376948108617
lat_025_mod -14.710706447106602
lat_025_mod -14.468766789118314
lat_025_mod -14.22656445497414
lat_025_mod -13.984101033081737
lat_025_mod -13.741383045143644
lat_025_mod -13.498412130373907
lat_025_mod -13.255194850331272
lat_025_mod -13.011732893627801
lat_025_mod -12.768032860624551
lat_025_mod -12.524096487886421
lat_025_mod -12.279930413485692
lat_025_mod -12.035536420458884
lat_025_mod -11.790921183462055
lat_025_mod -11.54608653048691
lat_025_mod -11.301039171610363
lat_025_mod -11.055780978228533
lat_025_mod -10.810318694641733
lat_025_mod -10.564654234066332
lat_025_mod -10.31879437379502
lat_025_mod -10.072741067247836
lat_025_mod -9.826501123446333
lat_025_mod -9.580076534366261
lat_025_mod -9.333474139463094
lat_025_mod -9.086695967590064
lat_025_mod -8.839748887311346
lat_025_mod -8.592634962650271
lat_025_mod -8.345361089925419
lat_025_mod -8.097929366594876
lat_025_mod -7.850346715349482
lat_025_mod -7.602615265320013
lat_025_mod -7.35474196416085
lat_025_mod -7.106728970887939
lat_025_mod -6.858583256685251
lat_025_mod -6.610307008642254
lat_025_mod -6.361907220014676
lat_025_mod -6.11338610413108
lat_025_mod -5.864750674838659
lat_025_mod -5.616003169849264
lat_025_mod -5.367150622100233
lat_025_mod -5.11819529181096
lat_025_mod -4.869144229488058
lat_025_mod -4.619999715964237
lat_025_mod -4.370768817776482
lat_025_mod -4.121453834459614
lat_025_mod -3.872061847025592
lat_025_mod -3.62259517178469
lat_025_mod -3.373060902653515
lat_025_mod -3.1234613707772407
lat_025_mod -2.8738036813934613
lat_025_mod -2.624090178529376
lat_025_mod -2.3743279771481918
lat_025_mod -2.1245194321955374
lat_025_mod -1.8746716667547774
lat_025_mod -1.6247870447172705
lat_025_mod -1.3748726956726578
lat_025_mod -1.1249309904778595
lat_025_mod -0.8749690636081526
lat_025_mod -0.6249892909000268
lat_025_mod -0.3749988100886759
lat_025_mod -0.125
lat_025_mod 0.125
lat_025_mod 0.3749988100886759
lat_025_mod 0.6249892909000268
lat_025_mod 0.8749690636081526
lat_025_mod 1.1249309904778595
lat_025_mod 1.3748726956726578
lat_025_mod 1.6247870447172705
lat_025_mod 1.8746716667547774
lat_025_mod 2.1245194321955374
lat_025_mod 2.3743279771481918
lat_025_mod 2.624090178529376
lat_025_mod 2.8738036813934613
lat_025_mod 3.1234613707772407
lat_025_mod 3.373060902653515
lat_025_mod 3.62259517178469
lat_025_mod 3.872061847025592
lat_025_mod 4.121453834459614
lat_025_mod 4.370768817776482
lat_025_mod 4.619999715964237
lat_025_mod 4.869144229488058
lat_025_mod 5.11819529181096
lat_025_mod 5.367150622100233
lat_025_mod 5.616003169849264
lat_025_mod 5.864750674838659
lat_025_mod 6.11338610413108
lat_025_mod 6.361907220014676
lat_025_mod 6.610307008642254
lat_025_mod 6.858583256685251
lat_025_mod 7.106728970887939
lat_025_mod 7.35474196416085
lat_025_mod 7.602615265320013
lat_025_mod 7.850346715349482
lat_025_mod 8.097929366594876
lat_025_mod 8.345361089925419
lat_025_mod 8.592634962650271
lat_025_mod 8.839748887311346
lat_025_mod 9.086695967590064
lat_025_mod 9.333474139463094
lat_025_mod 9.580076534366261
lat_025_mod 9.826501123446333
lat_025_mod 10.072741067247836
lat_025_mod 10.31879437379502
lat_025_mod 10.564654234066332
lat_025_mod 10.810318694641733
lat_025_mod 11.055780978228533
lat_025_mod 11.301039171610363
lat_025_mod 11.54608653048691
lat_025_mod 11.790921183462055
lat_025_mod 12.035536420458884
lat_025_mod 12.279930413485692
lat_025_mod 12.524096487886421
lat_025_mod 12.768032860624551
lat_025_mod 13.011732893627801
lat_025_mod 13.255194850331272
lat_025_mod 13.498412130373907
lat_025_mod 13.741383045143644
lat_025_mod 13.984101033081737
lat_025_mod 14.22656445497414
lat_025_mod 14.468766789118314
lat_025_mod 14.710706447106602
lat_025_mod 14.952376948108617
lat_025_mod 15.193776755893923
lat_025_mod 15.434899431481558
lat_025_mod 15.675743492150964
lat_025_mod 15.916302541708545
lat_025_mod 16.156575152237487
lat_025_mod 16.396554971229563
lat_025_mod 16.636240626826247
lat_025_mod 16.875625811062203
lat_025_mod 17.114709209351908
lat_025_mod 17.35348455908949
lat_025_mod 17.591950604136887
lat_025_mod 17.830101128022857
lat_025_mod 18.06793493419064
lat_025_mod 18.30544585303702
lat_025_mod 18.542632748679452
lat_025_mod 18.77948949907405
lat_025_mod 19.016015030064167
lat_025_mod 19.252203267814213
lat_025_mod 19.48805320090374
lat_025_mod 19.723558804311843
lat_025_mod 19.958719130323008
<xarray.DataArray 'sea_level_z0_025' (lat_025: 475, lon_025: 360)>
array([[      nan,       nan,       nan, ..., -0.000726, -0.000714, -0.000712],
       [      nan,       nan,       nan, ..., -0.000619, -0.000602, -0.000593],
       [      nan,       nan,       nan, ..., -0.000521, -0.000503, -0.00049 ],
       ...,
       [ 0.000569,  0.000628,  0.000692, ...,  0.001052,  0.000972,  0.000905],
       [ 0.000569,  0.000626,  0.000685, ...,  0.001087,  0.00102 ,  0.000952],
       [ 0.000562,  0.000635,  0.000698, ...,  0.001095,  0.001034,  0.000995]])
Coordinates:
  * lat_025  (lat_025) float64 -69.99 -69.88 -69.78 -69.67 ... 19.49 19.72 19.96
  * lon_025  (lon_025) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9

In [11]:
sea_level_z0_1_mod_xr = xr.DataArray(sea_level_z0_1_mod.transpose('yt_ocean', 'xt_ocean', 'year'), name='sea_level_z0_1_mod',
                        coords=[lat_1_mod, lon_1_mod, year], 
                        dims=['yt_ocean', 'xt_ocean', 'year'])
print(sea_level_z0_1_mod_xr)
sea_level_z0_1_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_mod.nc')

sea_level_z0_1_slope_mod_xr = xr.DataArray(sea_level_z0_1_slope_mod, name='sea_level_z0_1_slope_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_1_slope_mod_xr)
sea_level_z0_1_slope_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_slope_mod.nc')

sea_level_z0_1_p_value_mod_xr = xr.DataArray(sea_level_z0_1_p_value_mod, name='sea_level_z0_1_p_value_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_1_p_value_mod_xr)
sea_level_z0_1_p_value_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_p_value_mod.nc')

sea_level_z0_1_std_err_mod_xr = xr.DataArray(sea_level_z0_1_std_err_mod, name='sea_level_z0_1_std_err_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_1_std_err_mod_xr)
sea_level_z0_1_std_err_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_std_err_mod.nc')



sea_level_z0_025_mod_xr = xr.DataArray(sea_level_z0_025_mod.transpose('yt_ocean', 'xt_ocean', 'year'), name='sea_level_z0_025_mod',
                        coords=[lat_025_mod, lon_025_mod, year], 
                        dims=['yt_ocean', 'xt_ocean', 'year'])
print(sea_level_z0_025_mod_xr)
sea_level_z0_025_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_mod.nc')

sea_level_z0_025_slope_mod_xr = xr.DataArray(sea_level_z0_025_slope_mod, name='sea_level_z0_025_slope_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_025_slope_mod_xr)
sea_level_z0_025_slope_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_slope_mod.nc')

sea_level_z0_025_p_value_mod_xr = xr.DataArray(sea_level_z0_025_p_value_mod, name='sea_level_z0_025_p_value_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_025_p_value_mod_xr)
sea_level_z0_025_p_value_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_p_value_mod.nc')

sea_level_z0_025_std_err_mod_xr = xr.DataArray(sea_level_z0_025_std_err_mod, name='sea_level_z0_025_std_err_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_025_std_err_mod_xr)
sea_level_z0_025_std_err_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_std_err_mod.nc')

<xarray.DataArray 'sea_level_z0_1_mod' (yt_ocean: 160, xt_ocean: 90, year: 25)>
array([[[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [-1.804237, -1.79727 , ..., -1.801003, -1.803916],
        [-1.802819, -1.795696, ..., -1.79937 , -1.802256]],

       [[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [-1.802441, -1.795215, ..., -1.795574, -1.797055],
        [-1.800091, -1.792714, ..., -1.793039, -1.794382]],

       ...,

       [[ 0.570624,  0.552581, ...,  0.624408,  0.615035],
        [ 0.572101,  0.553011, ...,  0.632264,  0.622452],
        ...,
        [ 0.660109,  0.63699 , ...,  0.690162,  0.736722],
        [ 0.655128,  0.632463, ...,  0.68675 ,  0.737148]],

       [[ 0.579468,  0.559259, ...,  0.636086,  0.624793],
        [ 0.574604,  0.554437, ...,  0.638092,  0.626524],
        ...,
        [ 0.654862,  0.629591, ...,  0.686346,  0.725082],
        [ 0.649933,  0.62374 , ...,  0.683252,  0.726301]]], dtype=float32)
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * xt_ocean  (xt_ocean) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5
  * year      (year) int64 2233 2234 2235 2236 2237 ... 2253 2254 2255 2256 2257
<xarray.DataArray 'sea_level_z0_1_slope_mod' (yt_ocean: 160, xt_ocean: 90)>
array([[      nan,       nan,       nan, ..., -0.000443, -0.000411, -0.000392],
       [      nan,       nan,       nan, ..., -0.000392, -0.000361, -0.000339],
       [      nan,       nan,       nan, ..., -0.000365, -0.000341, -0.000331],
       ...,
       [ 0.001265,  0.001428,  0.0016  , ...,  0.000902,  0.000939,  0.000975],
       [ 0.001355,  0.001509,  0.001669, ...,  0.000865,  0.000918,  0.000963],
       [ 0.001435,  0.001606,  0.001793, ...,  0.000781,  0.000857,  0.000913]])
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * xt_ocean  (xt_ocean) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5
<xarray.DataArray 'sea_level_z0_1_p_value_mod' (yt_ocean: 160, xt_ocean: 90)>
array([[     nan,      nan,      nan, ..., 0.126266, 0.138659, 0.140788],
       [     nan,      nan,      nan, ..., 0.173647, 0.184779, 0.189615],
       [     nan,      nan,      nan, ..., 0.187622, 0.196398, 0.188922],
       ...,
       [0.026655, 0.01822 , 0.014047, ..., 0.266017, 0.246018, 0.231121],
       [0.020927, 0.015415, 0.011065, ..., 0.267205, 0.242435, 0.224676],
       [0.019904, 0.012401, 0.008671, ..., 0.297946, 0.258862, 0.235418]])
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * xt_ocean  (xt_ocean) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5
<xarray.DataArray 'sea_level_z0_1_std_err_mod' (yt_ocean: 160, xt_ocean: 90)>
array([[     nan,      nan,      nan, ..., 0.000279, 0.000268, 0.000257],
       [     nan,      nan,      nan, ..., 0.000279, 0.000264, 0.000251],
       [     nan,      nan,      nan, ..., 0.000269, 0.000256, 0.000245],
       ...,
       [0.000534, 0.000562, 0.000602, ..., 0.000791, 0.000788, 0.000793],
       [0.000546, 0.000577, 0.000604, ..., 0.000761, 0.000765, 0.000772],
       [0.000573, 0.000592, 0.000625, ..., 0.000734, 0.00074 , 0.000749]])
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * xt_ocean  (xt_ocean) float64 90.5 91.5 92.5 93.5 ... 176.5 177.5 178.5 179.5
<xarray.DataArray 'sea_level_z0_025_mod' (yt_ocean: 475, xt_ocean: 360, year: 25)>
array([[[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [-1.789115, -1.777881, ..., -1.787297, -1.791817],
        [-1.786906, -1.776043, ..., -1.785659, -1.790245]],

       [[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [-1.795144, -1.783839, ..., -1.789853, -1.793794],
        [-1.792828, -1.781937, ..., -1.787913, -1.791964]],

       ...,

       [[ 0.54418 ,  0.530977, ...,  0.592735,  0.561295],
        [ 0.545191,  0.528909, ...,  0.593659,  0.561771],
        ...,
        [ 0.630259,  0.606088, ...,  0.652826,  0.714924],
        [ 0.629798,  0.604389, ...,  0.650117,  0.711348]],

       [[ 0.550106,  0.534646, ...,  0.598827,  0.566657],
        [ 0.55009 ,  0.532006, ...,  0.599599,  0.567885],
        ...,
        [ 0.623799,  0.603604, ...,  0.652331,  0.715818],
        [ 0.623284,  0.601926, ...,  0.65008 ,  0.713085]]], dtype=float32)
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9
  * year      (year) int64 2233 2234 2235 2236 2237 ... 2253 2254 2255 2256 2257
<xarray.DataArray 'sea_level_z0_025_slope_mod' (yt_ocean: 475, xt_ocean: 360)>
array([[      nan,       nan,       nan, ..., -0.000726, -0.000714, -0.000712],
       [      nan,       nan,       nan, ..., -0.000619, -0.000602, -0.000593],
       [      nan,       nan,       nan, ..., -0.000521, -0.000503, -0.00049 ],
       ...,
       [ 0.000569,  0.000628,  0.000692, ...,  0.001052,  0.000972,  0.000905],
       [ 0.000569,  0.000626,  0.000685, ...,  0.001087,  0.00102 ,  0.000952],
       [ 0.000562,  0.000635,  0.000698, ...,  0.001095,  0.001034,  0.000995]])
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9
<xarray.DataArray 'sea_level_z0_025_p_value_mod' (yt_ocean: 475, xt_ocean: 360)>
array([[     nan,      nan,      nan, ..., 0.00192 , 0.002203, 0.002327],
       [     nan,      nan,      nan, ..., 0.005237, 0.006208, 0.006835],
       [     nan,      nan,      nan, ..., 0.014562, 0.017143, 0.019235],
       ...,
       [0.285749, 0.245424, 0.207508, ..., 0.242576, 0.274573, 0.305104],
       [0.308021, 0.269265, 0.234483, ..., 0.225913, 0.251525, 0.2802  ],
       [0.332368, 0.284505, 0.245453, ..., 0.220341, 0.244201, 0.259445]])
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9
<xarray.DataArray 'sea_level_z0_025_std_err_mod' (yt_ocean: 475, xt_ocean: 360)>
array([[     nan,      nan,      nan, ..., 0.000207, 0.000207, 0.000208],
       [     nan,      nan,      nan, ..., 0.000201, 0.0002  , 0.0002  ],
       [     nan,      nan,      nan, ..., 0.000197, 0.000196, 0.000195],
       ...,
       [0.00052 , 0.000527, 0.000534, ..., 0.000877, 0.000869, 0.000862],
       [0.000545, 0.000553, 0.000561, ..., 0.000873, 0.000867, 0.000861],
       [0.000568, 0.00058 , 0.000586, ..., 0.000869, 0.000865, 0.00086 ]])
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9